version: 0.2

phases:
  pre_build:
    commands:
      # Retrieve the SSH key from AWS Secrets Manager
      - aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:239302956728:secret:mac_ssh_key-Vb8f90 --query SecretString --output text > ./mackey.pem
      - chmod 600 ./mackey.pem

  build:
    commands:
      # SSH into the EC2 instance and echo the macOS version
      - ssh -i ./mackey.pem ec2-user@23.20.134.180 'sw_vers -productVersion' 
      - ssh -i ./mackey.pem ec2-user@23.20.134.180 'echo "macOS version on EC2 instance: $(sw_vers -productVersion)"'

