version: 0.2

phases:
  build:
    commands:
      - echo "$SSH_PRIVATE_KEY" > my-ssh-key.pem  # Store the private key in a file
      - chmod 400 my-ssh-key.pem
      - cat my-ssh-key.pem
      - ls -al
      - ssh -i my-ssh-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@18.208.222.103 "bash /Users/ec2-user/Documents/build.sh"

post_build:
  commands:
    - echo "This is a post-build step."
